[document]
    [document.margins]
    margin = 20
    line_end = 190

    [document.cells]
        [document.cells.standard]
        w = 0
        align = 'L'
        ln = 1
        [document.cells.left]
        w = 0
        align = 'L'
        ln = 0
        [document.cells.right]
        w = 0
        align = 'R'
        ln = 1
        [document.cells.multi]
        w = 0
        align = 'L'

    [document.styles]

        [document.styles.name]
        family = 'Times'
        style = 'B'
        size = 28
        [document.styles.title]
        family = 'Times'
        style = 'B'
        size = 18
        [document.styles.emphasis]
        family = 'Times'
        style = 'B'
        size = 12
        [document.styles.body]
        family = 'Times'
        style = ''
        size = 12